Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |v|
    v.name = "nginx"
    v.memory = 512
    v.cpus   = 1
  end

  config.vm.provision "shell", path: "setup.sh"

  config.vm.network "private_network", ip: "172.16.0.5", virtualbox__intnet: true
end
