Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |v|
    v.name = "openvpn"
    v.memory = 1024
    v.cpus   = 1
  end

  config.vm.provision "shell", path: "setup.sh"

  config.vm.network "private_network", ip: "192.168.10.5"
  config.vm.network "private_network", ip: "172.31.0.5", virtualbox__intnet: true
end
